## **Python for Data Analysis**
### **Módulo 2: Fundamentos de Python**
**Andrés C. Medina Sanhueza**

Lead Advanced Analytics Financial Retail Cencosud-Scotiabank

anmedinas@gmail.com

**Tópicos del Curso**
1. **Módulo 2 (Viernes 11 de Noviembre)**
  * Fundamentos de Python.
  * Operaciones, funciones y tipos de datos.
  * Variables y Operadores.
  * Strings.
  * Listas.
  * Diccionarios.
  * If-elif-else
  * Loops
  * While
  * Creacion de funciones y funciones con modulos
  * Numpy



---



# **Fundamentos de Python**

El intérprete de Python tiene una serie de funciones y tipos incluidos en él que están siempre disponibles. Están listados aquí en orden alfabético.

<tr>
<td><img src="figs/funciones_built.png" align="middle" style="width: 1000px;"/> </td>
</tr>

Para mayor información de cada función , revisar la [documentación de python](https://docs.python.org/es/3.8/library/functions.html)



En caso en que se desea tener una ayuda en relación a cualquiera de las funciones consideradas como *Built-in* o las funciones que están en cada módulo, la función indicada es ``help()``.

In [ ]:
help()


Welcome to Python 3.7's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the Internet at https://docs.python.org/3.7/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".



La función ``Globals()``retorna un diccionario que representa la tabla global de símbolos. Es siempre el diccionario del módulo actual (dentro de una función o método, este es el módulo donde está definida, no el módulo desde el que es llamada).

In [2]:
globals()

{'In': ['', 'help()', 'globals()'],
 'Out': {},
 '_': '',
 '__': '',
 '___': '',
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__loader__': None,
 '__name__': '__main__',
 '__package__': None,
 '__spec__': None,
 '_dh': ['/content'],
 '_i': 'help()',
 '_i1': 'help()',
 '_i2': 'globals()',
 '_ih': ['', 'help()', 'globals()'],
 '_ii': '',
 '_iii': '',
 '_oh': {},
 '_sh': <module 'IPython.core.shadowns' from '/usr/local/lib/python3.7/dist-packages/IPython/core/shadowns.py'>,
 'exit': <IPython.core.autocall.ZMQExitAutocall at 0x7f9a8a10a790>,
 'get_ipython': <bound method InteractiveShell.get_ipython of <google.colab._shell.Shell object at 0x7f9a8c8e28d0>>,
 'quit': <IPython.core.autocall.ZMQExitAutocall at 0x7f9a8a10a790>}

La función ``dir()`` sin argumentos, retorna la lista de nombres en el ámbito local. Con un argumento, intenta retornar una lista de atributos válidos para ese objeto.

In [3]:
dir()

['In',
 'Out',
 '_',
 '_2',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i2',
 '_i3',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 '_sh',
 'exit',
 'get_ipython',
 'quit']

De lo contrario, al usarse con un un argumento, devuelve una lista alfabética de nombres que comprende (alguno(s) de) los atributos de un objeto dato, y de los atributos legibles desde este.

In [4]:
dir(__builtins__)

['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BlockingIOError',
 'BrokenPipeError',
 'BufferError',
 'BytesWarning',
 'ChildProcessError',
 'ConnectionAbortedError',
 'ConnectionError',
 'ConnectionRefusedError',
 'ConnectionResetError',
 'DeprecationWarning',
 'EOFError',
 'Ellipsis',
 'EnvironmentError',
 'Exception',
 'False',
 'FileExistsError',
 'FileNotFoundError',
 'FloatingPointError',
 'FutureWarning',
 'GeneratorExit',
 'IOError',
 'ImportError',
 'ImportWarning',
 'IndentationError',
 'IndexError',
 'InterruptedError',
 'IsADirectoryError',
 'KeyError',
 'KeyboardInterrupt',
 'LookupError',
 'MemoryError',
 'ModuleNotFoundError',
 'NameError',
 'None',
 'NotADirectoryError',
 'NotImplemented',
 'NotImplementedError',
 'OSError',
 'OverflowError',
 'PendingDeprecationWarning',
 'PermissionError',
 'ProcessLookupError',
 'RecursionError',
 'ReferenceError',
 'ResourceWarning',
 'RuntimeError',
 'RuntimeWarning',
 'StopAsyncIteration',
 'StopIter

**Palabras Reservadas**

Se trata de una pequeña guía con el objetivo de dar a conocer las palabras reservadas o keywords de Python, aquellos nombres que incorpora el lenguaje los cuales no pueden ser reemplazados por un valor determinado (funciones, clases, variables) o alterar su funcionamiento. 

El modulo **keyword** se distribuye junto con la librería estándar de Python. Es generado automáticamente a partir del archivo graminit.c, perteneciente al código de fuente del intérprete. Incorpora una lista que contiene el conjunto de palabras resevadas, y una simple función que determina la existencia de un keyword a partir de una cadena. 


In [5]:
from keyword import iskeyword, kwlist
kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

## **1.Operaciones, Funciones, Tipos de Datos**

### **1.1 Operaciones Básicas**

<tr>
<td><img src="figs/basic-operators.png" align="middle" style="width: 1000px;"/> </td>
</tr>

In [ ]:
# Suma de dos numeros cualesquiera 
4 + 5

In [7]:
# Resta de dos numeros cualesquiera
1 - 3

-2

In [8]:
# Multiplicacion de dos numeros cualesquiera
5 * 8

40

In [9]:
# Division de dos numeros cualesquiera
3 / 2

1.5

In [10]:
# Potencia de un numero 
2**8

256

In [11]:
# Modulo de un numero
10 % 3

1

**Observación:** También existe la posibilidad de ingresar datos por terminal o consola utilizando la función ``input``. Ejemplo:

In [12]:
nota = input('Que dia es hoy? : ')

Que dia es hoy? : viernes


### **1.2. Tipos de Datos**

<tr>
<td><img src="figs/types_var.png" align="middle" style="width: 1000px;"/> </td>
</tr>

In [13]:
type(5)

int

In [14]:
type(0.5)

float

In [15]:
a = "Hola a todos"
type(a)

str

In [16]:
type(False)

bool

In [17]:
type({"Uno":1, "dos":2})

dict

In [18]:
type([1,2,3,4,5])

list

### **1.3. Operaciones con números flotantes**

In [19]:
2.5 + 3.6

6.1

In [20]:
4 + 56.4

60.4

In [21]:
5 + 8

13

In [22]:
# Resultado un numero flotante
4 / 2 

2.0

In [23]:
# Resultado un numero entero
4 // 2 

2

In [24]:
4 / 3.0

1.3333333333333333

In [25]:
4 // 3.0

1.0

### **1.4. Conversión**

In [26]:
float(9)

9.0

In [27]:
int(9.0)

9

In [28]:
int(6.5)

6

### **1.5. Función abs, round y pow**

In [29]:
abs(-3)

3

In [30]:
abs(3)

3

In [31]:
round(3.14151932,2)

3.14

In [32]:
# 4 elevado a 2
pow(4,2)

16

In [33]:
# 5 elevado a 3
pow(5,3)

125

## **2. Variables y Operadores**

### **2.1 Variables**

In [34]:
# Asigno un numero a una variable 
variable_1 = 2

In [35]:
variable_1

2

In [36]:
print(variable_1)

2


In [37]:
type(variable_1)

int

In [38]:
variable_2 = 3.141516

In [39]:
type(variable_2)

float

In [40]:
largo = 2 
alto  = 4

In [41]:
area = largo * alto
area 

8

In [42]:
perimetro = 2 * largo  + 2 * alto
perimetro  

12

In [43]:
id1 = 25
id2 = 35

In [44]:
id1 + id2

60

In [45]:
id1 - id2 

-10

In [46]:
id1 * id2 

875

In [47]:
id1 / id2 

0.7142857142857143

In [48]:
id2 % id1 

10

In [49]:
# Concatenacion de Variables 
nombre = "Elon"
apellido = "Musk"
nombre_completo = nombre + " " + apellido
print(nombre_completo)

Elon Musk


### **2.2. Declaración Múltiple**

In [50]:
persona_1, persona_2, persona_3 = "Carlos", "Cecilia", "Luis" 

In [51]:
persona_1

'Carlos'

In [52]:
persona_2

'Cecilia'

In [53]:
persona_3

'Luis'

In [54]:
fruta_1  = fruta_2 =  fruta_3 = "naranja" 

In [55]:
fruta_1 

'naranja'

Python, es sensible al uso de mayúsculas en las variables. 

In [56]:
Fruta_1

NameError: ignored

En Python, se pueden usar variables que comienzen con letras y después un número, **pero no al revés**. **No se pueden crear variables que comiencen con un número**. Ejemplo:

In [57]:
z1 = 20

In [58]:
1z

SyntaxError: ignored

## **3. Strings**

### **3.1 Creando Strings**

In [59]:
# Una palabra 
"Hola"

'Hola'

In [60]:
# Una frase 
"Creando strings en python"

'Creando strings en python'

In [61]:
# Podemos crear strings con comillas simples
"Creando strings en 'python'"

"Creando strings en 'python'"

In [62]:
print("Creando strings en python")

Creando strings en python


In [63]:
print('Creando \nStrings \nen \nPython')

Creando 
Strings 
en 
Python


### **3.2 Indexando Strings**

<tr>
<td><img src="figs/indexacion.png" align="middle" style="width: 1000px;"/> </td>
</tr>

In [64]:
s = "Creando strings en python"
print(s)

Creando strings en python


In [65]:
s[0]

'C'

In [66]:
s[1]

'r'

In [67]:
s[2]

'e'

In [68]:
# Para retornar todos los elementos de un string a partir 
# de cierta posicion, solo basta con poner :
s[1:]

'reando strings en python'

In [69]:
# Retornar el ultimo caracter del string 
s[-1]

'n'

In [70]:
# Retornar el string a partir del ultimo caracter
s[:-1]

'Creando strings en pytho'

In [71]:
s[::1]

'Creando strings en python'

In [72]:
s[::2]

'Cenosrnse yhn'

In [73]:
s[::-1]

'nohtyp ne sgnirts odnaerC'

In [74]:
# No se puede alterar un caracter
s[0] = 'K'

TypeError: ignored

In [75]:
# Concatenacion de Strings 
s + ' es muy aburrido'

'Creando strings en python es muy aburrido'

In [76]:
s = s + ' es muy aburrido'
print(s)

Creando strings en python es muy aburrido


### **3.3 Funciones Built-in de Strings (funciones integradas)**

In [77]:
s

'Creando strings en python es muy aburrido'

In [78]:
# Convierte a mayuscula el strings
s.upper() 

'CREANDO STRINGS EN PYTHON ES MUY ABURRIDO'

In [79]:
# convierte a minuscula el string
s.lower()

'creando strings en python es muy aburrido'

In [80]:
# Particiona el strings en caracteres (Textmining se conoce como tokenizacion)
s.split()

['Creando', 'strings', 'en', 'python', 'es', 'muy', 'aburrido']

In [81]:
# Divie el string en un caracter en especifico
s.split('s')

['Creando ', 'tring', ' en python e', ' muy aburrido']

In [82]:
# Genera una copia del string y convierte la primera letra a mayuscula (uppercase)
s.capitalize()

'Creando strings en python es muy aburrido'

In [83]:
# Cuenta cuantas 'e' hay en el string 
s.count('e')

3

In [84]:
# Encuentra la posicion indexada de la letra g
s.find('g')

13

## **4. Listas**

Una lista es una estructura de datos y un tipo de dato en python con características especiales. Lo especial de las listas en Python es que nos permiten almacenar cualquier tipo de valor como enteros, cadenas y hasta otras funciones; por ejemplo

In [85]:
lista = [1, 2.9, 'nombre', [5 , 6], 4]

In [86]:
print(lista[0]) # 1
print(lista[1]) # 2.9
print(lista[2]) # nombre
print(lista[3]) # [5,6]
print(lista[3][0]) # 5
print(lista[3][1]) # 6
print(lista[1:3]) # [2.9, 'nombre']
print(lista[1:6]) # [2.9, 'nombre', [5, 6], 4]

1
2.9
nombre
[5, 6]
5
6
[2.9, 'nombre']
[2.9, 'nombre', [5, 6], 4]


Como pueden darse cuenta podemos hasta insertar una lista dentro de otra lista.

In [87]:
# Algunas operaciones con listas 
listas = [[1,2,3], [10,15,14], [10.1,8.7,2.3]]

In [88]:
listas[0][0] # El indice 0 de la lista entrega el indice 0 de la lista [1,2,3]
listas[1][2] # El indice 1 de la lista entrega el indice 2 de la lista [10,15,14]
listas[0][2] # El indice 0 de la lista entrega el indice 2 de la lista [1,2,3]

3

In [89]:
# Al resultado de la lista entregada por lista[0][2] le sumo 10
listas[0][2] + 10

13

In [90]:
# Al resultado de la lista entregada por lista[0][2] multiplico por 5
listas[0][2] * 5

15

In [91]:
type(listas[0][2])

int

In [92]:
lista_2 = [100, 2, -5, 3.4]

In [93]:
max(lista_2) # 100
min(lista_2) # -5

-5

### **4.1 Append()**

Este método nos permite agregar nuevos elementos a una lista.

In [94]:
lista_1 = [1,  9.6, "listas", [1,2,3,4,5,6]]

In [95]:
lista_1.append(10)
print(lista_1)

[1, 9.6, 'listas', [1, 2, 3, 4, 5, 6], 10]


In [96]:
lista_1.append("nombres")
print(lista_1)

[1, 9.6, 'listas', [1, 2, 3, 4, 5, 6], 10, 'nombres']


Podemos agregar cualquier tipo de elemento a una lista, pero tengan en cuenta lo que pasa cuando agregamos una lista dentro de otra, esta lista se agrega como uno y solo un elemento.

### **4.2 Extend()**

Extend también nos permite agregar elementos dentro de una lista, pero a diferencia de append al momento de agregar una lista, cada elemento de esta lista se agrega como un elemento más dentro de la otra lista.

In [97]:
lista_1.extend([2,5]) 
print(lista_1)

[1, 9.6, 'listas', [1, 2, 3, 4, 5, 6], 10, 'nombres', 2, 5]


### **4.3 Remove()**

El método remove va a remover un elemento que se le pase como parámentro de la lista a donde se le esté aplicando.

In [98]:
type(lista_1)

list

In [99]:
lista_1.remove('nombres')
print(lista_1)

[1, 9.6, 'listas', [1, 2, 3, 4, 5, 6], 10, 2, 5]


In [100]:
len(lista_1)

7

También se puede eliminar elementos de la lista con la instrucción ``del``

In [101]:
del lista_1[6]

In [102]:
lista_1

[1, 9.6, 'listas', [1, 2, 3, 4, 5, 6], 10, 2]

### **4.4 Reverse()**

También podemos invertir los elementos  de una lista.

In [103]:
lista_1.reverse()
print(lista_1)

[2, 10, [1, 2, 3, 4, 5, 6], 'listas', 9.6, 1]


## **5. Diccionarios**

In [104]:
# Creacion de una Lista 
estudiantes = ["Mateo", 24, "Fernanda", 22, "Carlos", 26, "Cristina", 25]
estudiantes

['Mateo', 24, 'Fernanda', 22, 'Carlos', 26, 'Cristina', 25]

In [105]:
# Creacion de un diccionario
estudiantes_dict = {"Mateo":24, "Fernanda":22, "Carlos":26, "Cristina":25}
estudiantes_dict

{'Carlos': 26, 'Cristina': 25, 'Fernanda': 22, 'Mateo': 24}

In [106]:
estudiantes_dict["Mateo"]

24

In [107]:
# Si quiero agregar un nuevo item al diccionario
estudiantes_dict["Pedro"] = 28
estudiantes_dict

{'Carlos': 26, 'Cristina': 25, 'Fernanda': 22, 'Mateo': 24, 'Pedro': 28}

In [108]:
# largo del diccionario
len(estudiantes_dict)

5

In [109]:
# Acceso a el key del diccionario
estudiantes_dict.keys()

dict_keys(['Mateo', 'Fernanda', 'Carlos', 'Cristina', 'Pedro'])

In [110]:
# Acceso a los valores de los keys
estudiantes_dict.values()

dict_values([24, 22, 26, 25, 28])

In [111]:
# Diccionario visto como pares o items
estudiantes_dict.items()

dict_items([('Mateo', 24), ('Fernanda', 22), ('Carlos', 26), ('Cristina', 25), ('Pedro', 28)])

In [112]:
# Creo nuevo diccionario y actulizo el antiguo con el nuevo
estudiantes_2_dict = {"Jessica":26, "Andres": 27, "Dayana":28}
estudiantes_dict.update(estudiantes_2_dict)
estudiantes_dict

{'Andres': 27,
 'Carlos': 26,
 'Cristina': 25,
 'Dayana': 28,
 'Fernanda': 22,
 'Jessica': 26,
 'Mateo': 24,
 'Pedro': 28}

In [113]:
# Creo diccionario vacio y lo lleno con distintos tipos de datos
dic1 = {}
dic1["Uno"] = 1
dic1["Dos"] = 2 
dic1["Tres"] = 2.8
dic1["Cuatro"] = "Python"
dic1[5] = [22,25,26]
dic1

{5: [22, 25, 26], 'Cuatro': 'Python', 'Dos': 2, 'Tres': 2.8, 'Uno': 1}

In [114]:
# Si quiero limpiar el diccionario
estudiantes_dict.clear()
estudiantes_dict

{}

## **6. if-elif-else**

### **6.1. If Condicional**

In [115]:
6 > 3

True

In [116]:
3 > 7 

False

In [117]:
4 < 8 

True

In [118]:
if 5 > 2 :
  print("Es cierto!!! ")

Es cierto!!! 


In [119]:
if 5 < 2 : 
  print("Es cierto!!! ")
else:
  print("Algo esta fallando!!!") 


Algo esta fallando!!!


In [120]:
if 5 == 5 :
  print(" Si, 5 es identico a 5") 

 Si, 5 es identico a 5


In [121]:
edad = 18
if edad > 17:
  print("Eres mayor de 18")

Eres mayor de 18


In [122]:
nombre = "Lucas"
if edad > 13 :
  if nombre == "Lucas":
    print("Ok Lucas, puedes entrar, eres mayor de edad!")
  else :
    print("Sorry, no puedes entrar, eres menor de edad!")  

Ok Lucas, puedes entrar, eres mayor de edad!


In [123]:
edad = 21
nombre = "Bob"
if edad >= 18 and nombre == "Bob" : 
  print("Ok Bob, puedes ingresar!")

Ok Bob, puedes ingresar!


In [124]:
edad = 19
nombre = "Bob"
if (edad >= 18) or (nombre == "Bob") : 
  print("Ok Bob, puedes ingresar!")

Ok Bob, puedes ingresar!


### **6.2 elif**

In [125]:
dia = "lunes"
if dia == "martes":
  print("Si, es dia lunes")
else :
  print("No, es otro dia de la semana")

No, es otro dia de la semana


In [126]:
if dia == "lunes":
  print("Si, es dia lunes")
elif dia == "martes":
  print("Si, es dia martes")
else :
  print("No, es cualquier otro dia de la semana")

Si, es dia lunes


## **7. for**

In [127]:
# loop de una lista
v = [1,2,3,4,5]
for i in v:
  print(i)

1
2
3
4
5


In [128]:
# loop de  una tupla
t = (1,2,3,4,5,6)
for i in t:
  print(i)

1
2
3
4
5
6


In [129]:
# loop de un String
s = "Hola Clase"
for j in s:
  print(j)

H
o
l
a
 
C
l
a
s
e


In [130]:
# Loop de un Diccionario
d = {'p1':'Python','p2':'R','p3':'Matlab'}
for items in d:
  print(items)

p1
p2
p3


In [131]:
# Loop de un Diccionario
d = {'p1':'Python','p2':'R','p3':'Matlab'}
for k,v in d.items():
  print(k,v)

p1 Python
p2 R
p3 Matlab


In [132]:
# Loop de Listas 
lst = [[1,2,3], [3,4,5], "Hola Curso"]
for i in lst:
  print(i)

[1, 2, 3]
[3, 4, 5]
Hola Curso


In [133]:
# Loops Anidados 
for i in range(0,5):
  for j in range(6,10):
    print(j)

6
7
8
9
6
7
8
9
6
7
8
9
6
7
8
9
6
7
8
9


In [134]:
# Contando items de una lista 
lista = [1,2,3,4,5,6]
count = 0
for item in lista:
  count += 1
  print(count)

1
2
3
4
5
6


In [135]:
# Contando items de una lista (diferencia sutil de la posicion del print)
lista = [1,2,3,4,5,6]
count = 0
for item in lista:
  count += 1

print(count)

6


In [136]:
lista = [1,2,3,4,5]
for item in lista:
  if item == 3:
    print("Encontre el numero en la lista, y este es: ", item)

Encontre el numero en la lista, y este es:  3


## **8. range**

In [137]:
type(range(0,3))

range

In [138]:
for i in range(50, 101, 2):
    print(i)

50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100


In [139]:
for i in range(3, 6):
    print (i)

3
4
5


In [140]:
for i in range(0, -20, -2):
    print(i)

0
-2
-4
-6
-8
-10
-12
-14
-16
-18


In [141]:
lista = ['Mango', 'Platano', 'Fresas', 'Uvas']
lista_largo = len(lista)
for i in range(0, lista_largo):
    print(lista[i])

Mango
Platano
Fresas
Uvas


## **9. While**

In [142]:
# Usando loop para imprimir valores
count = 0 
while count < 10:
  print(count)
  count =  count + 1  

0
1
2
3
4
5
6
7
8
9


In [143]:
# While, if-else, breake y pass 
contador = 0
while contador < 100:
    if contador == 4:
        break
    else:
        pass
    print(contador)
    contador = contador + 1

0
1
2
3


In [144]:
# Verificando si un numero en un rango, es primo o no.
for i in range(2,30):
    j = 2
    contador = 0
    while j < i:
        if i % j == 0:
            contador = 1
            j = j + 1
        else:
            j = j + 1
    
    if contador == 0:
        print(str(i) + " es un numero primo")
        contador = 0
    else:
        contador = 0

2 es un numero primo
3 es un numero primo
5 es un numero primo
7 es un numero primo
11 es un numero primo
13 es un numero primo
17 es un numero primo
19 es un numero primo
23 es un numero primo
29 es un numero primo


## **9. Creación de Funciones**

In [145]:
# Funcion retorna un string 
def Hola():
  print("Hola Clase")

In [146]:
Hola()

Hola Clase


In [147]:
# Hola a "Alguien"
def HolaAlguien(nombre):
  print("Hola %s" %(nombre))

In [148]:
HolaAlguien("Lucas")

Hola Lucas


In [149]:
# Funcion que crea potencias 
def potencia(numero):
  result = numero**2
  return result

In [150]:
potencia(5)

25

In [151]:
# Funcion que crea potencias 
def potencia(numero):
  return numero**2

En Python, una función Lambda se refiere a una pequeña función anónima. Las llamamos```funciones anónimas``` porque técnicamente carecen de nombre. Al contrario que una función normal, no la definimos con la palabra clave estándar def que utilizamos en Python.

In [152]:
# Funcion que crea potencias 
def potencia(numero): return numero**2

In [153]:
# Definiendo expresiones lambda 
potencia = lambda num: num**2

In [154]:
# Funcion que calcula promedio 
def promedio(vector):
  n = len(vector)
  xbar = sum(x)/n
  return xbar 

In [155]:
x = [1,2,3,4,5,6,7,8]
promedio(x)

4.5

In [156]:
type(promedio(x))

float

In [157]:
# funcion que lee un vector en un loop
def lectura_vector():
  for i in range(0,5):
    print("numero " + str(i))

In [158]:
lectura_vector() 

numero 0
numero 1
numero 2
numero 3
numero 4


In [159]:
# funcion que particiona un string 
def split_string(text):
  return text.split(" ")

In [160]:
texto = "Hola a todos, como estan"
split_string(texto)

['Hola', 'a', 'todos,', 'como', 'estan']

## **10. NumPy**

**NumPy** es la librería de python especializada en el cálculo numérico y análisis de datos, especialmente para un gran volumen de datos.

<tr>
<td><img src="figs/numpy_global.jpeg" align="middle" style="width: 1000px;"/> </td>
</tr>



Para invocar este módulo, python utiliza un sistema de importación en el cual, se obtiene acceso al código y a las funciones declaradas en él. Por ejemplo, si quiero importar el módulo numpy y utilizar toda la bateria de funciones que tiene éste, lo invoco de la siguiente manera: 




In [161]:
import numpy

Para revisar la versión de numpy que maneja colab, basta con tipear en la linea de comandos:

In [162]:
numpy.version.version

'1.19.5'

In [163]:
# Dado un vector, obtengo la media de este
x = [1,2,3,4,5,6,7,8,9,10]
numpy.mean(x)

5.5

Para ver todas las funciones que trae el módulo numpy, utilicemos la función ``dir()`` vista anteriormente.

In [164]:
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_

In [165]:
import numpy as np

# Dado un vector x , se calcula la media
x = [1,2,3,4,5,6,7,8,9,10]
np.mean(x)

5.5

### **11.1. Arrays**

Un array o arreglo ``Numpy`` es un colección N-dimensional homogénea de ítems del mismo tipo. El tipo, puede ser cualquier estructura arbitraria de bytes y es especificada usando tipos de datos. Un arreglo contiene:
* Valores de un experimento/simulación en intervalos de tiempo discreto.
* Señal grabada de un dispositivo de medición, por ejemplo, onda de sonido.
* Pixeles de una imagen en escala de grises o en color.
* Datos en 3D que miden diferentes posiciones XYZ.

```Numpy``` es el encargado de añadir toda la capacidad matemática y vectorial a ```Python``` haciendo posible operar con cualquier dato numérico o array. Incorpora operaciones tan básicas como la suma o la multiplicación u otras mucho más complejas como la transformada de Fourier o el álgebra lineal. Además incorpora herramientas que nos permiten incorporar código fuente de otros lenguajes de programación como ```C/C++``` o ```Fortran``` lo que incrementa notablemente su compatibilidad e implementación.

Un array es el término que traslada el concepto matemático de vector o matriz a la programación añadiéndole la noción de almacenamiento en memoria. Los arrays disponen en su interior de una serie de elementos dispuestos en filas y/o columnas dependiendo de la dimensión. El desarrollo y la principal finalidad del módulo Numpy es la creación y modificación de arrays multidimensionales. 

<tr>
<td><img src="figs/np_03.png" align="middle" style="width: 1000px;"/> </td>
</tr>

Algunas instrucciones utiles son:
* **ndarray.ndim** : Proporciona el número de dimensiones de nuestro array. 
* **ndarray.shape** : Devuelve el tamaño del array en cada dimensión. Para una matriz obtendremos ($n$,$m$).
* **ndarray.size** : Es el número total de elementos del array.
* **ndarray.dtype** : Es un objeto que describe el tipo de elementos del array.
* **ndarray.itemsize**: devuelve el tamaño del array en bytes.
* **ndarray.data** : El buffer contiene los elementos actuales del array.

In [166]:
x = np.array([0,1,2,3,4])
print(x)

[0 1 2 3 4]


In [167]:
# Dimension del array 
x.ndim # 1
# Forma del array
x.shape # 5
# Taman~o del array 
x.size  # 5
# Tipo del array
x.dtype # dtype('int64')

dtype('int64')

In [168]:
x.dtype

dtype('int64')

Como hemos mencionando anteriormente, los arrays son unos de los elementos más utilizados por los programadores bajo cualquier lenguaje. Este gran uso hace que dispongamos de una gran variedad de comandos para la creación de arrays: arrays unidimensionales, multidimensionales, nulos, unitarios, secuenciales, de números aleatorios, etc. Dependiendo de las necesidades de nuestro problema escogeremos la opción más adecuada.

Algunas funciones utiles son:
* **identity** : Genera una matriz identidad.
* **ones** : Genera un array de unos.
* **zeros**: Genera un array de ceros.
* **empty**: Genera un array vacio o sin entradas
* **eye** : Genera un array bidimensional con unos en la diagonal $k$ y ceros en el resto.
* **arange** : Genera un array con valores distanciados entre un valor inicial y uno final.
* **linspace** : Genera un array con valor inicial, final, y numeros de elementos.
* **mesgrid** : Genera una matriz de coordenadas a partir de dos arrays $x$, $y$.

In [169]:
# Matriz Identidad
np.identity((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [170]:
# Matriz con unos en la diagonal
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [171]:
# Matriz de Zeros
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [172]:
# Matriz de Unos 
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**¿Cómo accedo a los elementos de una matriz ?**

Considere la siguiente matriz:

<tr>
<td><img src="figs/np_02.png" align="middle" style="width: 1000px;"/> </td>
</tr>

In [ ]:
a = np.array([[0,1,2,3,4,5],
              [10,11,12,13,14,15],
              [20,21,22,23,24,25],
              [30,31,32,33,34,35],
              [40,41,42,43,44,45],
              [50,51,52,53,54,55]])

In [ ]:
a[0,3:5]
a[4:,4:]
a[:,2]
a[2::2,::2]

array([[20, 22, 24],
       [40, 42, 44]])

Un tensor es son objetos matemáticos que almacenan valores numéricos y que pueden tener distintas dimensiones. Así, por ejemplo, un tensor de 1D es un vector, de 2D una matriz, de 3D un cubo etc. ... En Python, estos tensores normalmente se almacenan en lo que se conoce como NumPy arrays.

<tr>
<td><img src="figs/tensor.jpg" align="middle" style="width: 1000px;"/> </td>
</tr>

**Observación:** La utilización de tensores tiene sentido cuando se utilizan redes neuronales convolucionales. Herramientas como Pytorch y Tensorflow son las más adecuadas a la hora de implementar arquitecturas de este tipo.

<img src="https://raw.githubusercontent.com/jmv74211/Redes_neuronales/master/images/figura8.png" width=500 height=400 />

### **11.2. Funciones para crear arrays**

**Array uniformemente espaciado**

In [173]:
## Genera un array de 0 ... n-1
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [174]:
## Genera un array de innicio, final, y un paso o delta
b = np.arange(1,9,2) 
b

array([1, 3, 5, 7])

**Array espaciado por puntos**

In [175]:
# Inicio, final, numero de puntos 
c = np.linspace(0,1,6) 
c

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [176]:
d = np.linspace(0,1,5,endpoint=False)
d

array([0. , 0.2, 0.4, 0.6, 0.8])

In [177]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [178]:
a.shape

(3, 5)

In [179]:
a.ndim

2

In [180]:
a.size

15

In [181]:
## Array 1D
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [182]:
## Array 2d
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [183]:
## Array 3d
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


**Operaciones Básicas**

In [184]:
a = np.array([1, 2, 3, 6])
b = np.linspace(0, 2, 4)
c = a - b
c

array([1.        , 1.33333333, 1.66666667, 4.        ])

In [185]:
a**2

array([ 1,  4,  9, 36])

In [186]:
a = np.linspace(-np.pi, np.pi, 100) 
b = np.sin(a)
c = np.cos(a)

In [187]:
x = np.array([[1,2],[3,4]])
np.sum(x)           # Calcula la suma de todo los elementos de la matriz x 
np.sum(x, axis=0)   # Calcula la suma de cada columna 
np.sum(x, axis=1)   # Calcula la suma de cada fila

array([3, 7])

### **11.3. Algebra Lineal**

In [188]:
from numpy.random import rand
from numpy.linalg import solve, inv

# Crea una matriz 
a = np.array([[1, 2, 3], [3, 4, 6.7], [5, 9.0, 5]])
a

array([[1. , 2. , 3. ],
       [3. , 4. , 6.7],
       [5. , 9. , 5. ]])

In [189]:
# Transpone una matriz
a.transpose()

array([[1. , 3. , 5. ],
       [2. , 4. , 9. ],
       [3. , 6.7, 5. ]])

In [190]:
# Inversa de la matriz
inv(a)

array([[-2.27683616,  0.96045198,  0.07909605],
       [ 1.04519774, -0.56497175,  0.1299435 ],
       [ 0.39548023,  0.05649718, -0.11299435]])

In [191]:
# Resuelvo Ecuacion
a = np.array([[1, 2, 3], [3, 4, 6.7], [5, 9.0, 5]])
b = np.array([3, 2, 1])
solve(a,b)

array([-4.83050847,  2.13559322,  1.18644068])

In [192]:
# Matriz aleatoria en el intervalo [0, 1] escalado por 20
c = rand(3, 3) * 20
c

array([[ 1.61031295, 19.73178776, 11.48579048],
       [10.35624419,  9.82487352, 19.39758518],
       [17.29550642,  1.07635592, 17.76560595]])

In [193]:
# Multiplacion de Matrices
np.dot(a, c)

array([[ 74.2093206 ,  42.61060257, 103.57777869],
       [162.13580864, 105.70644205, 231.07727202],
       [187.73529459, 192.46458012, 320.83524876]])

In [194]:
# Multiplicacion de Matrices (versiones de python > 3.5 y numpy 1.10)
a @ c

array([[ 74.2093206 ,  42.61060257, 103.57777869],
       [162.13580864, 105.70644205, 231.07727202],
       [187.73529459, 192.46458012, 320.83524876]])

### **11.4 Funciones Estadísticas**

<tr>
<td><img src="figs/stats.png" align="middle" style="width: 1000px;"/> </td>
</tr>

**Algunas funciones**

* **np.amin():** Calcula el valor mínimo de un array.
* **np.amax():** Calcula el valor máximo de un array.
* **np.mean():** Calcula la media de un conjunto de datos.
* **np.median():** Calcula la mediana de un conjunto de datos.
* **np.std():** Calcula la desviación estandar
* **np.var():** Calcula la varianza 
* **np.average():** Calcula la media ponderada
* **np.percentile:** Determinal el percentil n-ésimo de un conjunto de datos.

In [195]:
import numpy as np
y = np.array([[1,23,78],[98,60,75],[79,25,48]])  
y

array([[ 1, 23, 78],
       [98, 60, 75],
       [79, 25, 48]])

In [196]:
# Minimo
np.min(y)

1

In [197]:
# Maximo
np.max(y)

98

In [198]:
# Promedio
np.mean(y)

54.111111111111114

In [199]:
# Mediana
np.median(y)

60.0

In [200]:
# Desviacion Standar
np.std(y)

30.296477405960523

In [201]:
# Varianza
np.var(y)

917.8765432098766

In [202]:
# Media Ponderada
a = np.array([5,6,7]) 
wt = np.array([8,2,3])
np.average(a, weights=wt)

5.615384615384615

In [203]:
# Percentil
a = np.array([2,10,20])  
np.percentile(a,10,0)

3.6

¿Y como obtengo la media geométrica ?

$$\bar{x} = \left(\prod_{i=1}^{n} x_{i}\right)^{1/n}$$

In [204]:
import numpy as np

def geom_media(x):
  a = np.array(x)
  return a.prod()**(1/len(a))

In [205]:
geom_media([1.0, 0.00001, 10000000000.])

46.41588833612778

Para corroborar el valor, la función de media geométrica no se encuentra en numpy, pero si se encuentra en scipy como ``gmean``

In [206]:
from scipy.stats.mstats import gmean
gmean([1.0, 0.00001, 10000000000.])

46.415888336127786



---



**Ejercicio : Mínimos Cuadrados Regularizados** 

* De acuerdo al siguiente modelo
estadistico

$$
\begin{eqnarray*}
\epsilon &\sim& \mathcal{N}(0_p,\sigma^2{\bf{I}}_{nn}) \\
Y &\sim& \mathcal{N}(X\beta,\sigma^2{\bf{I}}_{nn})
\end{eqnarray*}
$$

Implementar matricialmente el estimador de minimos cuadrados ordinarios (MCO) y regularizados usando funciones de numpy.

$$
\begin{eqnarray*}
\widehat{\beta}_{MCO} &=& (X^{t}X)^{-1}X^{t}Y \\
\widehat{\beta}_{RR} &=& (X^{t}X + \rho{\bf{I}})^{-1}X^{t}Y 
\end{eqnarray*}
$$

Donde $\rho=1$ represneta a regularizaciones LASSO y $\rho=2$ representa a regularizaciones Ridge.

In [207]:
import numpy as np

# Parametros 
mu, sigma, n = 0, 0.5, 10 

# Vectores aleatorios normales 
Y = np.random.normal(mu, sigma, n)
X = np.random.normal(mu, sigma, n)

In [208]:
# Genero una nueva matriz X 
np.column_stack((np.ones(n),X))

array([[ 1.        , -0.1654563 ],
       [ 1.        ,  0.14133726],
       [ 1.        , -1.14780139],
       [ 1.        ,  0.3013323 ],
       [ 1.        ,  1.00361296],
       [ 1.        , -0.03879601],
       [ 1.        ,  0.43298757],
       [ 1.        ,  0.45611217],
       [ 1.        ,  0.28876771],
       [ 1.        , -0.13240755]])

In [209]:
# Estimador Minimos Cuadradros Ordinarios 
Xnew = np.column_stack((np.ones(n),X))
beta = inv(Xnew.transpose() @ Xnew) @ Xnew.transpose() @ Y 
beta

array([0.10626033, 0.07538078])

In [210]:
# Estimador Minimos Cuadradros Regularizados 
rho  = 0 
Xnew = np.column_stack((np.ones(n),X))
beta = inv(Xnew.transpose()@Xnew + rho*np.identity((Xnew.ndim))) @ Xnew.transpose() @ Y 
beta

array([0.10626033, 0.07538078])

In [211]:
# Comprobacion con libreria statmodels (tambien se solicita cargar pandas)
import pandas as pd
import warnings

import statsmodels.api as sm
warnings.filterwarnings("ignore")

Xnew2   = sm.add_constant(X)
model   = sm.OLS(Y,Xnew2) 
results = model.fit()
print(results.summary())

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.012
Model:                            OLS   Adj. R-squared:                 -0.112
Method:                 Least Squares   F-statistic:                   0.09683
Date:                Fri, 12 Nov 2021   Prob (F-statistic):              0.764
Time:                        03:26:14   Log-Likelihood:                -4.0987
No. Observations:                  10   AIC:                             12.20
Df Residuals:                       8   BIC:                             12.80
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.1063      0.132      0.806      0.4